[[services]]
name       = "backend"
root       = "."
dockerfile = "apps/backend/Dockerfile"
restart    = "on-failure"

  [services.env]
  PORT = "3001"
  DATABASE_URL = "mysql://{{MYSQLUSER}}:{{MYSQLPASSWORD}}@{{MYSQLHOST}}:{{MYSQLPORT}}/{{MYSQLDATABASE}}"

  [services.deploy]
  startCommand = "node dist/src/main.js"

    [services.deploy.healthcheck]
    path    = "/health"
    timeout = 120
